// <auto-generated />
namespace BibliotecaDDD.Infra.Data.Entity.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FilmeCreate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FilmeCreate));
        
        string IMigrationMetadata.Id
        {
            get { return "201802131323333_FilmeCreate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
